import "../globals.css"
import type { Metadata } from "next"
import { Rubik } from "next/font/google"
import React from "react"
import Header from "@/components/header/Header"
import Footer from "@/components/footer/Footer"
import { Providers } from "@/redux/providers"

const rubik = Rubik({ subsets: ["latin"] })

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={rubik.className}>
                <Header />
                <main>
                    <Providers>{children}</Providers>
                </main>
                <Footer />
            </body>
        </html>
    )
}
