import "../globals.css"
import { Metadata } from "next"
import React from "react"
import { Rubik } from "next/font/google"
import BackBtn from "@/components/auth/BackBtn"

const rubik = Rubik({ subsets: ["latin"] })

export const metadata: Metadata = {
    title: "OZ | Authentication",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" className={"rubik.className"}>
            <body className={"bg-[#F5F6F8]"}>
                <header className={"absolute top-0 left-0"}>
                    <BackBtn />
                </header>
                <main className="w-full h-full flex justify-center items-center">
                    {children}
                </main>
            </body>
        </html>
    )
}
