import "../globals.css"
import { Metadata } from "next"
import React from "react"
import { Rubik } from "next/font/google"
import BackBtn from "@/components/auth/BackBtn"
import { Providers } from "@/redux/providers"

const rubik = Rubik({ subsets: ["latin"] })

export const metadata: Metadata = {
    title: "OZ | Authentication",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" className={"rubik.className"}>
            <body className={"bg-[#F5F6F8]"}>
                <header className={"absolute top-0 left-0 z-10"}>
                    <BackBtn className="p-4 text-black text-3xl" />
                </header>
                <main className="w-full h-full flex justify-center items-center">
                    <Providers>{children}</Providers>
                </main>
            </body>
        </html>
    )
}
