import "../globals.css"
import type { Metadata } from "next"
import { Rubik } from "next/font/google"
import React from "react"
import { Providers } from "@/redux/providers"

const rubik = Rubik({ subsets: ["latin"] })

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={rubik.className}>
                <main className="pb-12 w-full bg-[linear-gradient(to_bottom,#FF971D_60vh,#F5F6F899_60vh)]">
                    <Providers>{children}</Providers>
                </main>
            </body>
        </html>
    )
}
