import "../globals.css"
import { Providers } from "@/redux/providers"
import React from "react"
import Header from "@/components/header/Header"
import Footer from "@/components/footer/Footer"

export const metadata = {
    title: "OZ",
    description: "Generated by Next.js",
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body>
                <Header />
                <Providers>
                    <main className={"bg-[#F5F6F8] py-20"}>{children}</main>
                </Providers>
                <Footer />
            </body>
        </html>
    )
}
